/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.grib;

import java.io.FileNotFoundException;
import java.io.IOException;

import net.sourceforge.jgrib.GribFile;
import net.sourceforge.jgrib.NoValidGribException;
import net.sourceforge.jgrib.NotSupportedException;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name = "Grib", id = "de.appwerft.grib")
public class GribModule extends KrollModule {

	private static final String LCAT = "GribModule";

	public GribModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {

	}

	@Kroll.method
	public String decode(String filename) {
		// Reading of grib files must be inside a try-catch block
		try {
			GribFile gribFile = new GribFile(filename);
			gribFile.getGrids();

		} catch (FileNotFoundException noFileError) {
			System.err.println("FileNotFoundException : " + noFileError);
		} catch (IOException ioError) {
			System.err.println("IOException : " + ioError);
		} catch (NoValidGribException noGrib) {
			System.err.println("NoValidGribException : " + noGrib);
		} catch (NotSupportedException noSupport) {
			System.err.println("NotSupportedException : " + noSupport);
		}
		return "";

	}

}
